runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  APP_KEY: base64:mZjVqjAitoVz49Mu2Vv7Zdie1zH7S3FA/lW/Uaol7/I=
  STORAGE_DIR: /tmp